version: "3"
services:
  # mongodb:
  #   image: "mongo:latest"
  #   ports:
  #     - 27017:27017
  graphql-server:
    build:
      context: "./"
    ports:
      - 4000:4000
    environment:
      - mongoURI=mongodb://admin:T2fOEtAmGddNL9Ae@SG-playground-20964.servers.mongodirector.com:48469,SG-playground-20965.servers.mongodirector.com:48469,SG-playground-20966.servers.mongodirector.com:48469/admin?replicaSet=RS-playground-0&ssl=true
