version: "3"
services:
  mongodb:
    image: "mongo:latest"
    ports:
      - 27017:27017
  graphql-server:
    build:
      context: "./"
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
      - mongoURI=mongodb://mongodb:27017/graphql-development
# version: "2"

# services:
#   mongodb-primary:
#     image: "bitnami/mongodb:latest"
#     environment:
#       - MONGODB_REPLICA_SET_MODE=primary
#       - MONGODB_REPLICA_SET_NAME=rs0
#       - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
#       #- MONGODB_REPLICA_SET_KEY=rs0
#       # - MONGODB_ROOT_PASSWORD=1234

#     volumes:
#       - "mongodb_master_data:/bitnami"

#   mongodb-secondary:
#     image: "bitnami/mongodb:latest"
#     depends_on:
#       - mongodb-primary
#     environment:
#       - MONGODB_REPLICA_SET_MODE=secondary
#       - MONGODB_PRIMARY_HOST=mongodb-primary
#       - MONGODB_PRIMARY_PORT_NUMBER=27017
#       #- MONGODB_REPLICA_SET_KEY=rs0
#       # - MONGODB_PRIMARY_ROOT_PASSWORD=1234

#   mongodb-arbiter:
#     image: "bitnami/mongodb:latest"
#     depends_on:
#       - mongodb-primary
#     environment:
#       - MONGODB_REPLICA_SET_MODE=arbiter
#       - MONGODB_PRIMARY_HOST=mongodb-primary
#       - MONGODB_PRIMARY_PORT_NUMBER=27017
#       #- MONGODB_REPLICA_SET_KEY=rs0
#       #- MONGODB_PRIMARY_ROOT_PASSWORD=1234

#   graphql-server:
#     build:
#       context: "./"
#     ports:
#       - 4000:4000
#     depends_on:
#       - mongodb-primary
#     environment:
#       - mongoURI=mongodb://mongodb-primary/graphql-development?replicaSet=rs0

# volumes:
#   mongodb_master_data:
#     driver: local
